[package]
name = "hyperspeed"
version = "0.1.0"
authors = ["Jackson Lewis <st.japa6@gmail.com>"]
edition = "2018"

[dependencies]
specs = "0.14.3"
cascade = "0.1.3"
serde = "1.0.90"
serde_derive = "1.0.90"
bytes = "0.4.12"
serde_json = "1.0.39"